### ISSUE TITLE
Root Ownership of Home Directory

### ISSUE THREAD

**Issue by KyleMondron** [LeBoldus-Lab/Cluster_Tutorial#2]
I was able to talk to Ken from CGRB to get access to CGRB. 

However, I currently must not belong to the bpp group. The owner of my home directory (/home/bpp/mondronk according to cd ~) is root (whereas the other directories I see have that user as the owner) and the group is bpp, but I am not part of BPP, so I have no access and even cd ~ failed to let me go to there. 

@Tabima , is this something you can do, or should I talk to the CGRB staff again?

**Comment by Tabima** [comment]
Hey Kyle, that's a CGRB thing. Can you send them an email, please?

**Comment by KyleMondron** [comment]
Javier,

I jumped the gun and sent them a service request regarding that! :) 

I also posted an issue in the github, but that was primarily because I wanted to explore the issues feature! ;)

Thanks,
KTM
________________________________________

**Comment by Tabima** [comment]
haha nice, keep me posted.

thanks for using GitHub!
-
Javier F. Tabima R., Ph. D.

Postdoctoral scholar
Spatafora Lab
LeBoldus Lab

Botany and Plant Pathology Department.
Oregon State University, 
Corvallis, OR.

**Comment by KyleMondron** [comment]
Closed because CGRB staff seem to have fixed this issue.
